# Generated by Django 5.1.1 on 2024-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data',
            field=models.CharField(default='fill', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
